# Generated by Django 3.2.8 on 2023-03-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0005_workexperience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='company',
            field=models.CharField(max_length=100),
        ),
    ]
