# Generated by Django 3.2.8 on 2023-03-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myportfolio', '0006_alter_workexperience_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('education_level', models.CharField(choices=[('Primary', 'Primary'), ('Seconadry', 'Secondary'), ('Tertiary', 'Tertiary'), ('Master', 'Master'), ('Phd', 'Phd')], max_length=100)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
